# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Raw/home.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(969, 775)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_middle = QtWidgets.QFrame(self.centralwidget)
        self.frame_middle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_middle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_middle.setObjectName("frame_middle")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_middle)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_left = QtWidgets.QFrame(self.frame_middle)
        self.frame_left.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.frame_left.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left.setObjectName("frame_left")
        self.gridLayout_left_frame = QtWidgets.QGridLayout(self.frame_left)
        self.gridLayout_left_frame.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_left_frame.setSpacing(0)
        self.gridLayout_left_frame.setObjectName("gridLayout_left_frame")
        self.horizontalLayout.addWidget(self.frame_left)
        self.frame_right = QtWidgets.QFrame(self.frame_middle)
        self.frame_right.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_right.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_right.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_right.setObjectName("frame_right")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_right)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_shapes = QtWidgets.QGroupBox(self.frame_right)
        self.groupBox_shapes.setMinimumSize(QtCore.QSize(0, 120))
        self.groupBox_shapes.setMaximumSize(QtCore.QSize(16777215, 120))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.groupBox_shapes.setFont(font)
        self.groupBox_shapes.setStyleSheet("QGroupBox{\n"
"    border: 2px groove gray;\n"
"    border-width: 4px 2px 2px 1px;\n"
"    border-color: gray;\n"
"    margin-top: 10px;\n"
"    font-size: 14px;\n"
"    border-radius: 15px;\n"
"}\n"
"QGroupBox:title{\n"
"    border-radius: 5px;\n"
"    background-color: rgba(182, 182, 182, 150);\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    padding: 2px;\n"
"    padding-right: 10px;\n"
"    padding-left: 10px;\n"
"}")
        self.groupBox_shapes.setObjectName("groupBox_shapes")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_shapes)
        self.gridLayout.setObjectName("gridLayout")
        self.radioButton_curve = QtWidgets.QRadioButton(self.groupBox_shapes)
        self.radioButton_curve.setObjectName("radioButton_curve")
        self.gridLayout.addWidget(self.radioButton_curve, 1, 1, 1, 1)
        self.radioButton_square = QtWidgets.QRadioButton(self.groupBox_shapes)
        self.radioButton_square.setObjectName("radioButton_square")
        self.gridLayout.addWidget(self.radioButton_square, 3, 0, 1, 1)
        self.radioButton_circle = QtWidgets.QRadioButton(self.groupBox_shapes)
        self.radioButton_circle.setObjectName("radioButton_circle")
        self.gridLayout.addWidget(self.radioButton_circle, 1, 0, 1, 1)
        self.radioButton_line = QtWidgets.QRadioButton(self.groupBox_shapes)
        self.radioButton_line.setObjectName("radioButton_line")
        self.gridLayout.addWidget(self.radioButton_line, 2, 0, 1, 1)
        self.radioButton_polyline = QtWidgets.QRadioButton(self.groupBox_shapes)
        self.radioButton_polyline.setObjectName("radioButton_polyline")
        self.gridLayout.addWidget(self.radioButton_polyline, 2, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_shapes)
        self.groupBox_penSize = QtWidgets.QGroupBox(self.frame_right)
        self.groupBox_penSize.setMinimumSize(QtCore.QSize(0, 80))
        self.groupBox_penSize.setMaximumSize(QtCore.QSize(16777215, 120))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.groupBox_penSize.setFont(font)
        self.groupBox_penSize.setStyleSheet("QGroupBox{\n"
"    border: 2px groove gray;\n"
"    border-width: 4px 2px 2px 1px;\n"
"    border-color: gray;\n"
"    margin-top: 10px;\n"
"    font-size: 14px;\n"
"    border-radius: 15px;\n"
"}\n"
"QGroupBox:title{\n"
"    border-radius: 5px;\n"
"    background-color: rgba(182, 182, 182, 150);\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    padding: 2px;\n"
"    padding-right: 10px;\n"
"    padding-left: 10px;\n"
"}")
        self.groupBox_penSize.setObjectName("groupBox_penSize")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_penSize)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_show_pen_size = QtWidgets.QLabel(self.groupBox_penSize)
        self.label_show_pen_size.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_show_pen_size.setObjectName("label_show_pen_size")
        self.verticalLayout_6.addWidget(self.label_show_pen_size)
        self.horizontalSlider_penSize = QtWidgets.QSlider(self.groupBox_penSize)
        self.horizontalSlider_penSize.setMinimum(1)
        self.horizontalSlider_penSize.setMaximum(30)
        self.horizontalSlider_penSize.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_penSize.setObjectName("horizontalSlider_penSize")
        self.verticalLayout_6.addWidget(self.horizontalSlider_penSize)
        self.comboBox = QtWidgets.QComboBox(self.groupBox_penSize)
        self.comboBox.setEnabled(True)
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_6.addWidget(self.comboBox)
        self.verticalLayout_2.addWidget(self.groupBox_penSize)
        self.groupBox_penColor = QtWidgets.QGroupBox(self.frame_right)
        self.groupBox_penColor.setMinimumSize(QtCore.QSize(0, 120))
        self.groupBox_penColor.setMaximumSize(QtCore.QSize(16777215, 120))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.groupBox_penColor.setFont(font)
        self.groupBox_penColor.setStyleSheet("QGroupBox{\n"
"    border: 2px groove gray;\n"
"    border-width: 4px 2px 2px 1px;\n"
"    border-color: gray;\n"
"    margin-top: 10px;\n"
"    font-size: 14px;\n"
"    border-radius: 15px;\n"
"}\n"
"QGroupBox:title{\n"
"    border-radius: 5px;\n"
"    background-color: rgba(182, 182, 182, 150);\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    padding: 2px;\n"
"    padding-right: 10px;\n"
"    padding-left: 10px;\n"
"}")
        self.groupBox_penColor.setObjectName("groupBox_penColor")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_penColor)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_show_pen_color = QtWidgets.QLabel(self.groupBox_penColor)
        self.label_show_pen_color.setMinimumSize(QtCore.QSize(50, 50))
        self.label_show_pen_color.setMaximumSize(QtCore.QSize(50, 50))
        self.label_show_pen_color.setText("")
        self.label_show_pen_color.setObjectName("label_show_pen_color")
        self.gridLayout_6.addWidget(self.label_show_pen_color, 0, 0, 1, 1)
        self.pushButton_pickColor = QtWidgets.QPushButton(self.groupBox_penColor)
        self.pushButton_pickColor.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_pickColor.setObjectName("pushButton_pickColor")
        self.gridLayout_6.addWidget(self.pushButton_pickColor, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_penColor)
        self.groupBox_text = QtWidgets.QGroupBox(self.frame_right)
        self.groupBox_text.setMinimumSize(QtCore.QSize(0, 200))
        self.groupBox_text.setMaximumSize(QtCore.QSize(16777215, 350))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.groupBox_text.setFont(font)
        self.groupBox_text.setStyleSheet("QGroupBox{\n"
"    border: 2px groove gray;\n"
"    border-width: 4px 2px 2px 1px;\n"
"    border-color: gray;\n"
"    margin-top: 10px;\n"
"    font-size: 14px;\n"
"    border-radius: 15px;\n"
"}\n"
"QGroupBox:title{\n"
"    border-radius: 5px;\n"
"    background-color: rgba(182, 182, 182, 150);\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    padding: 2px;\n"
"    padding-right: 10px;\n"
"    padding-left: 10px;\n"
"}")
        self.groupBox_text.setObjectName("groupBox_text")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_text)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_6 = QtWidgets.QFrame(self.groupBox_text)
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setHorizontalSpacing(0)
        self.gridLayout_4.setVerticalSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_text_inp_pos = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_text_inp_pos.setCheckable(True)
        self.pushButton_text_inp_pos.setObjectName("pushButton_text_inp_pos")
        self.gridLayout_4.addWidget(self.pushButton_text_inp_pos, 2, 0, 1, 1)
        self.lineEdit_input_text = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_input_text.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_input_text.setObjectName("lineEdit_input_text")
        self.gridLayout_4.addWidget(self.lineEdit_input_text, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_6)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_6, 4, 0, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.groupBox_text)
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.frame_7)
        self.label.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.fontComboBox_text = QtWidgets.QFontComboBox(self.frame_7)
        self.fontComboBox_text.setObjectName("fontComboBox_text")
        self.gridLayout_2.addWidget(self.fontComboBox_text, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_7, 1, 0, 1, 1)
        self.frame_8 = QtWidgets.QFrame(self.groupBox_text)
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalSlider_fontSize = QtWidgets.QSlider(self.frame_8)
        self.horizontalSlider_fontSize.setMinimum(8)
        self.horizontalSlider_fontSize.setMaximum(30)
        self.horizontalSlider_fontSize.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_fontSize.setObjectName("horizontalSlider_fontSize")
        self.gridLayout_5.addWidget(self.horizontalSlider_fontSize, 1, 0, 1, 1)
        self.label_font_size = QtWidgets.QLabel(self.frame_8)
        self.label_font_size.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_font_size.setObjectName("label_font_size")
        self.gridLayout_5.addWidget(self.label_font_size, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_8, 3, 0, 1, 1)
        self.frame_9 = QtWidgets.QFrame(self.groupBox_text)
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 5)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_3 = QtWidgets.QLabel(self.frame_9)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_3.setObjectName("label_3")
        self.gridLayout_7.addWidget(self.label_3, 0, 0, 1, 1)
        self.comboBox_LineStyle = QtWidgets.QComboBox(self.frame_9)
        self.comboBox_LineStyle.setObjectName("comboBox_LineStyle")
        self.gridLayout_7.addWidget(self.comboBox_LineStyle, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_9, 2, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_text)
        self.horizontalLayout.addWidget(self.frame_right)
        self.verticalLayout.addWidget(self.frame_middle)
        self.frame_bottom = QtWidgets.QFrame(self.centralwidget)
        self.frame_bottom.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_bottom.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_bottom.setObjectName("frame_bottom")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_bottom)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_mouse_pointer = QtWidgets.QFrame(self.frame_bottom)
        self.frame_mouse_pointer.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_mouse_pointer.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_mouse_pointer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_mouse_pointer.setObjectName("frame_mouse_pointer")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_mouse_pointer)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_pointer = QtWidgets.QLabel(self.frame_mouse_pointer)
        self.label_pointer.setText("")
        self.label_pointer.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pointer.setObjectName("label_pointer")
        self.verticalLayout_5.addWidget(self.label_pointer)
        self.horizontalLayout_2.addWidget(self.frame_mouse_pointer)
        self.frame_4 = QtWidgets.QFrame(self.frame_bottom)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_bottom_persistent_message = QtWidgets.QLabel(self.frame_4)
        self.label_bottom_persistent_message.setText("")
        self.label_bottom_persistent_message.setObjectName("label_bottom_persistent_message")
        self.horizontalLayout_3.addWidget(self.label_bottom_persistent_message)
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.verticalLayout.addWidget(self.frame_bottom)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 969, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuImage = QtWidgets.QMenu(self.menubar)
        self.menuImage.setObjectName("menuImage")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionReset = QtWidgets.QAction(MainWindow)
        self.actionReset.setObjectName("actionReset")
        self.actionLoad_Image = QtWidgets.QAction(MainWindow)
        self.actionLoad_Image.setObjectName("actionLoad_Image")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionLoad_SVG = QtWidgets.QAction(MainWindow)
        self.actionLoad_SVG.setObjectName("actionLoad_SVG")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionExit)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionLoad_Image)
        self.menuFile.addAction(self.actionLoad_SVG)
        self.menuImage.addAction(self.actionReset)
        self.menuImage.addAction(self.actionUndo)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuImage.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ventor graphic editor"))
        self.groupBox_shapes.setTitle(_translate("MainWindow", "Shapes"))
        self.radioButton_curve.setText(_translate("MainWindow", "Curve"))
        self.radioButton_square.setText(_translate("MainWindow", "Square"))
        self.radioButton_circle.setText(_translate("MainWindow", "Circle"))
        self.radioButton_line.setText(_translate("MainWindow", "Line"))
        self.radioButton_polyline.setText(_translate("MainWindow", "Poly Line"))
        self.groupBox_penSize.setTitle(_translate("MainWindow", "Pen Size"))
        self.label_show_pen_size.setText(_translate("MainWindow", "Pen Size: "))
        self.groupBox_penColor.setTitle(_translate("MainWindow", "Pen Color"))
        self.pushButton_pickColor.setText(_translate("MainWindow", "pick color"))
        self.groupBox_text.setTitle(_translate("MainWindow", "Text"))
        self.frame_6.setToolTip(_translate("MainWindow", "Click on the button and then click on the canvas, \n"
"o set the top-left position of the text frame to input."))
        self.pushButton_text_inp_pos.setText(_translate("MainWindow", "Set font input position"))
        self.label_2.setText(_translate("MainWindow", "Text to input"))
        self.label.setText(_translate("MainWindow", "Select font family"))
        self.label_font_size.setText(_translate("MainWindow", "Select font size (current )"))
        self.label_3.setText(_translate("MainWindow", "Select Line Style"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuImage.setTitle(_translate("MainWindow", "Image"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionReset.setText(_translate("MainWindow", "Reset"))
        self.actionReset.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionLoad_Image.setText(_translate("MainWindow", "Load Image"))
        self.actionLoad_Image.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionLoad_SVG.setText(_translate("MainWindow", "Load SVG"))
